# Generated by Django 4.0.4 on 2022-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default='2022-7-26 04:02'),
        ),
    ]
